const models=[
 {name:'Gemini',provider:'Google',tags:['reasoning','coding','vision','free'],note:'Strong general-purpose family with multimodal capabilities and developer API access.',url:'https://ai.google.dev/'},
 {name:'Qwen',provider:'Alibaba / Qwen',tags:['reasoning','coding','vision','free'],note:'Open-weight family with strong coding and multilingual options.',url:'https://qwenlm.github.io/'},
 {name:'DeepSeek',provider:'DeepSeek',tags:['reasoning','coding'],note:'Reasoning and coding-focused models; API availability and pricing vary by endpoint.',url:'https://platform.deepseek.com/'},
 {name:'Mistral',provider:'Mistral AI',tags:['reasoning','coding','vision'],note:'Open and hosted models with strong multilingual and coding coverage.',url:'https://docs.mistral.ai/'},
 {name:'Llama',provider:'Meta',tags:['reasoning','coding','vision'],note:'Broad open-weight ecosystem with many hosted and local deployments.',url:'https://www.llama.com/'},
 {name:'GLM',provider:'Z.ai',tags:['reasoning','coding','free'],note:'General and coding-oriented models available through hosted APIs and open ecosystems.',url:'https://docs.z.ai/'},
 {name:'Nemotron',provider:'NVIDIA',tags:['reasoning','coding','free'],note:'NVIDIA model family; selected free endpoints can be available through model platforms.',url:'https://developer.nvidia.com/nemotron'},
 {name:'Liquid LFM',provider:'Liquid AI',tags:['reasoning','coding','free'],note:'Compact efficient models suited to latency-sensitive and edge-oriented workloads.',url:'https://www.liquid.ai/'},
 {name:'Cohere Command',provider:'Cohere',tags:['reasoning','coding'],note:'Enterprise-oriented language models and retrieval-focused API tooling.',url:'https://docs.cohere.com/'}
];
const providers=[
 {name:'Google AI Studio',type:'Direct API',note:'Developer access to Gemini. Check the current official quota and model availability.',url:'https://aistudio.google.com/'},
 {name:'Groq',type:'Inference API',note:'Fast hosted inference with an OpenAI-compatible API surface for supported models.',url:'https://console.groq.com/'},
 {name:'OpenRouter',type:'Multi-provider',note:'One API surface across many model providers. Free model availability changes over time.',url:'https://openrouter.ai/'},
 {name:'Hugging Face',type:'Model ecosystem',note:'Models, Spaces and inference options across a large open-model ecosystem.',url:'https://huggingface.co/'},
 {name:'Cloudflare Workers AI',type:'Edge inference',note:'Hosted inference integrated with Cloudflare developer infrastructure.',url:'https://developers.cloudflare.com/workers-ai/'},
 {name:'Mistral API',type:'Direct API',note:'Official hosted access to Mistral models; verify current free/developer allowances.',url:'https://console.mistral.ai/'},
 {name:'Cohere',type:'Direct API',note:'Official API for Command and retrieval-oriented capabilities.',url:'https://dashboard.cohere.com/'},
 {name:'AI21',type:'Direct API',note:'Jamba and related model/API resources; verify current developer terms.',url:'https://studio.ai21.com/'}
];
const services=[
 {name:'OmniRoot',role:'Local system / hardware agent',detail:'Installed locally. Activation requires the local bridge.',endpoint:'omniroot'},
 {name:'OpenCode',role:'Local coding agent',detail:'Installed locally. Activation requires the local bridge.',endpoint:'opencode'},
 {name:'OpenCore',role:'Local core service',detail:'Installed locally. Activation requires the local bridge.',endpoint:'opencore'}
];
let filter='all';
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderModels(){const q=document.querySelector('#modelSearch').value.toLowerCase();const list=models.filter(m=>(filter==='all'||m.tags.includes(filter))&&(`${m.name} ${m.provider} ${m.note} ${m.tags.join(' ')}`.toLowerCase().includes(q)));document.querySelector('#modelCount').textContent=`${list.length} indexed`;document.querySelector('#modelGrid').innerHTML=list.map(m=>`<article class="card"><div class="card-top"><span class="tag">${esc(m.provider)}</span><span class="tag">${m.tags.includes('free')?'FREE ACCESS':'API'}</span></div><h3>${esc(m.name)}</h3><p>${esc(m.note)}</p><div class="chips">${m.tags.map(t=>`<span class="chip">${t}</span>`).join('')}</div><a class="provider-link" href="${m.url}" target="_blank" rel="noreferrer" style="display:inline-block;margin-top:16px;color:#aaa;font-size:10px">Official source ↗</a></article>`).join('')||'<div class="muted">No models match the current filter.</div>'}
function renderProviders(){document.querySelector('#providerGrid').innerHTML=providers.map(p=>`<article class="provider"><div class="provider-top"><span class="tag">${esc(p.type)}</span><span class="tag">RESOURCE</span></div><h3>${esc(p.name)}</h3><p>${esc(p.note)}</p><a href="${p.url}" target="_blank" rel="noreferrer">Open official resource ↗</a></article>`).join('')}
function renderServices(states={}){document.querySelector('#localGrid').innerHTML=services.map(s=>{const state=states[s.endpoint]||'inactive';return `<article class="local-card"><div class="local-top"><span class="tag">LOCAL</span><span class="state ${state==='connected'?'ready':''}">${state.toUpperCase()}</span></div><h3>${esc(s.name)}</h3><p>${esc(s.role)}<br>${esc(s.detail)}</p><button class="activate" data-service="${s.endpoint}">Open / Activate</button></article>`}).join('');document.querySelectorAll('.activate').forEach(b=>b.addEventListener('click',()=>activate(b.dataset.service)))}
async function checkBridge(){const dot=document.querySelector('#bridgeDot'),status=document.querySelector('#bridgeStatus'),badge=document.querySelector('#bridgeBadge'),message=document.querySelector('#bridgeMessage');try{const r=await fetch('http://127.0.0.1:8765/status',{method:'GET',headers:{Accept:'application/json'}});if(!r.ok)throw new Error('unavailable');const data=await r.json();dot.style.background='var(--green)';dot.style.boxShadow='0 0 16px #15846e';status.textContent='Local bridge connected';badge.textContent='CONNECTED';message.textContent='The local companion is reachable. Service controls can now send authenticated local requests.';renderServices(data.services||{})}catch(e){dot.style.background='#555';dot.style.boxShadow='none';status.textContent='Local bridge inactive';badge.textContent='OFFLINE';message.textContent='No local bridge detected at 127.0.0.1:8765. The site remains fully usable as a public registry.';renderServices({})}}
async function activate(service){try{const r=await fetch(`http://127.0.0.1:8765/activate/${encodeURIComponent(service)}`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({source:'sanjib-ai-hub',requestedAt:new Date().toISOString()})});if(!r.ok)throw new Error('activation failed');await checkBridge()}catch(e){alert('Local bridge is not connected. Nothing was started.')} }
document.querySelector('#modelSearch').addEventListener('input',renderModels);document.querySelectorAll('#modelFilters button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#modelFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderModels()}));document.querySelector('#bridgeCheck').addEventListener('click',checkBridge);renderModels();renderProviders();renderServices({});
const canvas=document.querySelector('#field'),ctx=canvas.getContext('2d');let pts=[];function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);pts=Array.from({length:55},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.12,vy:(Math.random()-.5)*.12}))}function animate(){ctx.clearRect(0,0,innerWidth,innerHeight);for(const p of pts){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>innerWidth)p.vx*=-1;if(p.y<0||p.y>innerHeight)p.vy*=-1;ctx.fillStyle='rgba(128,82,255,.55)';ctx.fillRect(p.x,p.y,1,1)}for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){const a=pts[i],b=pts[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<115){ctx.strokeStyle=`rgba(128,82,255,${(1-d/115)*.08})`;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}requestAnimationFrame(animate)}addEventListener('resize',resize);resize();animate();
